[package]

name = "rust-jack"
description = "JACK Audio Connection Kit bindings for Rust"
version = "0.0.1"
authors = ["Nick Lanham <nick@afternight.org>", "Miranda Kastemaa <miranda@foldplop.com>"]
repository = "https://github.com/ahihi/rust-jack"
readme = "README.md"
keywords = ["jack", "audio", "music", "sound"]
license = "LGPL-2.1"

[lib]
name="jack"

[dependencies]
libc = "0.1"
bitflags = "0.1"
getopts = "0.2"
